version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["angular"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  max_line_length = 99
  runtime_version = "3.x.x"