[build-system]
requires = ["setuptools>=60.6", "wheel"]
buld-backend = "setuptools.build_neta"

[pytest]
python_files = "test_*.py *_tests.py tests.py"
cache_dir = "tmp/.pytest_cache"

[mypy]
cache_dir = "tmp/.mypy_cache"
plugins = "mypy_django_plugin.main"
strict_optional = "True"
