name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r backend/requirements_dev.txt
    - name: Run black
      run:
        black --check backend/src/ --line-length 99
    - name: Run flake8
      run: flake8 backend/src --config backend/tox.ini
    - name: Run test
      run: |
        cd backend
        python manage.py test
    - name: Run Mypy
      run: |
        cd backend
        mypy src --config-file setup.cfg --no-incremental

  migration_job:
    runs-on: ubuntu-latest
    name: CI migration
    steps:
      # Checkout the source code
      - name: Checkout
        uses: actions/checkout@v2

      # Run database migrations with the public action
      - name: Check database migrations with DLE
        uses: postgres-ai/dle-github-action@v0.1.1
        id: db-migrations
        with:
          dbname: test
          commands: |
            cd backend
            py manage.py makemigration
          download_artifacts: true
          observation_interval: "10"
          max_lock_duration: "1"
          max_duration: "600"
      - name: Testing
        run: |
          cd backend
          py manage.py test
            
